# Generated by Django 4.0 on 2022-08-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='code',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
